function isoDaysFromNow(days) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

function isoDateOnlyDaysFromNow(days) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export function createMockDbSeed() {
  const workflowStages = [
    {
      id: "6993579cad61306bbed982b6",
      name: "Planning",
      description: "Initial planning and scoping phase",
      order: 0,
      color: "blue",
      is_active: true,
      require_approval: false,
      allowed_transitions: [],
      created_date: "2026-02-17T03:36:28.460Z",
      updated_date: "2026-02-17T03:36:28.460Z",
    },
    {
      id: "6993579cad61306bbed982b7",
      name: "In Progress",
      description: "Active development and execution",
      order: 1,
      color: "yellow",
      is_active: true,
      require_approval: false,
      allowed_transitions: [],
      created_date: "2026-02-17T03:36:28.460Z",
      updated_date: "2026-02-17T03:36:28.460Z",
    },
    {
      id: "6993579cad61306bbed982b8",
      name: "Review",
      description: "Under review and quality assurance",
      order: 2,
      color: "purple",
      is_active: true,
      require_approval: true,
      allowed_transitions: [],
      created_date: "2026-02-17T03:36:28.460Z",
      updated_date: "2026-02-17T03:36:28.460Z",
    },
    {
      id: "6993579cad61306bbed982b9",
      name: "Completed",
      description: "Successfully completed tasks",
      order: 3,
      color: "green",
      is_active: true,
      require_approval: false,
      allowed_transitions: [],
      created_date: "2026-02-17T03:36:28.460Z",
      updated_date: "2026-02-17T03:36:28.460Z",
    },
    {
      id: "6993579cad61306bbed982ba",
      name: "On Hold",
      description: "Tasks temporarily paused",
      order: 4,
      color: "gray",
      is_active: true,
      require_approval: false,
      allowed_transitions: [],
      created_date: "2026-02-17T03:36:28.460Z",
      updated_date: "2026-02-17T03:36:28.460Z",
    },
  ];

  const departments = [
    { id: "dept_td", name: "Tourism Development", sector: "Tourism", description: "Tourism development initiatives", manager_user_id: "user1", manager_name: "Ahmed Al-Mansouri", member_count: 17, email: "tourism@department.gov", is_active: true, created_date: isoDaysFromNow(-200) },
    { id: "dept_mp", name: "Marketing & Promotion", sector: "Marketing", description: "Marketing and promotional activities", manager_user_id: "user2", manager_name: "Fatima Al-Kitbi", member_count: 16, email: "marketing@department.gov", is_active: true, created_date: isoDaysFromNow(-200) },
    { id: "dept_eh", name: "Events & Hospitality", sector: "Hospitality", description: "Events coordination and hospitality", manager_user_id: "user3", manager_name: "Mohammed Al-Zahrani", member_count: 13, email: "events@department.gov", is_active: true, created_date: isoDaysFromNow(-200) },
    { id: "dept_hc", name: "Heritage & Culture", sector: "Culture", description: "Cultural heritage preservation", manager_user_id: "user1", manager_name: "Ahmed Al-Mansouri", member_count: 12, email: "heritage@department.gov", is_active: true, created_date: isoDaysFromNow(-200) },
    { id: "dept_fa", name: "Finance & Administration", sector: "Administration", description: "Financial operations and administration", manager_user_id: "user2", manager_name: "Fatima Al-Kitbi", member_count: 14, email: "finance@department.gov", is_active: true, created_date: isoDaysFromNow(-200) },
    { id: "dept_it", name: "Information Technology", sector: "Technology", description: "IT infrastructure and digital services", manager_user_id: "user3", manager_name: "Mohammed Al-Zahrani", member_count: 15, email: "it@department.gov", is_active: true, created_date: isoDaysFromNow(-200) },
    { id: "dept_lc", name: "Legal & Compliance", sector: "Legal", description: "Legal affairs and compliance", manager_user_id: "user1", manager_name: "Ahmed Al-Mansouri", member_count: 7, email: "legal@department.gov", is_active: true, created_date: isoDaysFromNow(-200) },
    { id: "dept_cm", name: "Communications", sector: "Communications", description: "Public relations and communications", manager_user_id: "user2", manager_name: "Fatima Al-Kitbi", member_count: 11, email: "communications@department.gov", is_active: true, created_date: isoDaysFromNow(-200) },
    { id: "dept_hd", name: "Human Development", sector: "Training", description: "Training and human development", manager_user_id: "user3", manager_name: "Mohammed Al-Zahrani", member_count: 8, email: "training@department.gov", is_active: true, created_date: isoDaysFromNow(-200) },
    { id: "dept_qs", name: "Quality & Standards", sector: "Quality", description: "Quality assurance and standards", manager_user_id: "user1", manager_name: "Ahmed Al-Mansouri", member_count: 10, email: "quality@department.gov", is_active: true, created_date: isoDaysFromNow(-200) },
    { id: "dept_ra", name: "Research & Analytics", sector: "Research", description: "Research and data analytics", manager_user_id: "user2", manager_name: "Fatima Al-Kitbi", member_count: 12, email: "research@department.gov", is_active: true, created_date: isoDaysFromNow(-200) },
    { id: "dept_su", name: "Sustainability", sector: "Environment", description: "Environmental sustainability initiatives", manager_user_id: "user3", manager_name: "Mohammed Al-Zahrani", member_count: 9, email: "sustainability@department.gov", is_active: true, created_date: isoDaysFromNow(-200) },
  ];

  const users = [
    {
      id: "user1",
      full_name: "Ahmed Al-Mansouri",
      full_name_ar: "أحمد المنصوري",
      email: "ahmed.mansouri@tourism.gov",
      role: "admin",
      department: "Tourism Development",
      department_id: "dept_td",
      position: "Director of Tourism",
      phone: "+971-50-123-4567",
      avatar_url: "",
      onboarding_completed: true,
      notification_preferences: { email_assignments: true, email_due_reminders: true, email_mentions: true, in_app_all: true },
      mailboxes: [{ id: "mb_gov", email: "gov@department.gov", displayName: "Government Inbox", provider: "outlook", isActive: true }],
      created_date: isoDaysFromNow(-365),
      updated_date: isoDaysFromNow(-1),
    },
    {
      id: "user2",
      full_name: "Fatima Al-Kitbi",
      full_name_ar: "فاطمة الكتبي",
      email: "fatima.kitbi@tourism.gov",
      role: "department_admin",
      department: "Marketing & Promotion",
      department_id: "dept_mp",
      position: "Deputy Director",
      phone: "+971-50-123-4568",
      avatar_url: "",
      onboarding_completed: true,
      created_date: isoDaysFromNow(-300),
      updated_date: isoDaysFromNow(-1),
    },
    {
      id: "user3",
      full_name: "Mohammed Al-Zahrani",
      full_name_ar: "محمد الزهراني",
      email: "mohammed.zahrani@tourism.gov",
      role: "department_manager",
      department: "Events & Hospitality",
      department_id: "dept_eh",
      position: "Senior Manager",
      phone: "+971-50-123-4569",
      avatar_url: "",
      onboarding_completed: true,
      created_date: isoDaysFromNow(-240),
      updated_date: isoDaysFromNow(-1),
    },
    {
      id: "6979b622cb93ec17bdd5d627",
      full_name: "Mohamed Elnaggar",
      full_name_ar: "محمد النجار",
      email: "moh.hassan81@gmail.com",
      role: "admin",
      department: "Tourism Development",
      department_id: "dept_td",
      position: "System Administrator",
      phone: "+971-50-123-4570",
      avatar_url: "",
      onboarding_completed: true,
      created_date: isoDaysFromNow(-365),
      updated_date: isoDaysFromNow(-1),
    },
  ];

  // Real Team Members from Base44 export
  const teamMembers = [
    { id: "699486cf6860a0380869ae5d", ext_no: "1001", name: "Ahmed Al Mansouri", email: "ahmed.mansouri@tourism.gov", job_title: "Director of Tourism", department_name: "Tourism Development", sector_name: "Tourism", organization_name: "Ministry of Tourism", reporting_to: "Head of Department", telephone_number: "+971-4-123-4567", mobile_number: "+971-50-123-4567", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae5e", ext_no: "1002", name: "Fatima Al Khaleej", email: "fatima.khaleej@tourism.gov", job_title: "Deputy Director", department_name: "Tourism Development", sector_name: "Tourism", organization_name: "Ministry of Tourism", reporting_to: "Ahmed Al Mansouri", telephone_number: "+971-4-123-4568", mobile_number: "+971-50-123-4568", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae5f", ext_no: "1003", name: "Mohammed Al Neyadi", email: "mohammed.neyadi@tourism.gov", job_title: "Senior Manager", department_name: "Tourism Development", sector_name: "Tourism", organization_name: "Ministry of Tourism", reporting_to: "Fatima Al Khaleej", telephone_number: "+971-4-123-4569", mobile_number: "+971-50-123-4569", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae60", ext_no: "1004", name: "Layla Al Mansouri", email: "layla.mansouri@tourism.gov", job_title: "Project Manager", department_name: "Tourism Development", sector_name: "Tourism", organization_name: "Ministry of Tourism", reporting_to: "Mohammed Al Neyadi", telephone_number: "+971-4-123-4570", mobile_number: "+971-50-123-4570", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae61", ext_no: "1005", name: "Hassan Al Zaabi", email: "hassan.zaabi@tourism.gov", job_title: "Senior Coordinator", department_name: "Tourism Development", sector_name: "Tourism", organization_name: "Ministry of Tourism", reporting_to: "Mohammed Al Neyadi", telephone_number: "+971-4-123-4571", mobile_number: "+971-50-123-4571", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae62", ext_no: "1006", name: "Amna Al Ketbi", email: "amna.ketbi@tourism.gov", job_title: "Specialist", department_name: "Tourism Development", sector_name: "Tourism", organization_name: "Ministry of Tourism", reporting_to: "Layla Al Mansouri", telephone_number: "+971-4-123-4572", mobile_number: "+971-50-123-4572", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae63", ext_no: "1007", name: "Ibrahim Al Mazrouei", email: "ibrahim.mazrouei@tourism.gov", job_title: "Analyst", department_name: "Tourism Development", sector_name: "Tourism", organization_name: "Ministry of Tourism", reporting_to: "Hassan Al Zaabi", telephone_number: "+971-4-123-4573", mobile_number: "+971-50-123-4573", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae64", ext_no: "1008", name: "Sara Al Falasi", email: "sara.falasi@tourism.gov", job_title: "Officer", department_name: "Tourism Development", sector_name: "Tourism", organization_name: "Ministry of Tourism", reporting_to: "Hassan Al Zaabi", telephone_number: "+971-4-123-4574", mobile_number: "+971-50-123-4574", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae65", ext_no: "2001", name: "Omar Al Sharji", email: "omar.sharji@tourism.gov", job_title: "Coordinator", department_name: "Marketing & Promotion", sector_name: "Marketing", organization_name: "Ministry of Tourism", reporting_to: "Layla Al Mansouri", telephone_number: "+971-4-123-4575", mobile_number: "+971-50-123-4575", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae66", ext_no: "2002", name: "Hana Al Qasimi", email: "hana.qasimi@tourism.gov", job_title: "Content Creator", department_name: "Marketing & Promotion", sector_name: "Marketing", organization_name: "Ministry of Tourism", reporting_to: "Omar Al Sharji", telephone_number: "+971-4-123-4576", mobile_number: "+971-50-123-4576", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae67", ext_no: "2003", name: "Khalid Al Maktoum", email: "khalid.maktoum@tourism.gov", job_title: "Digital Manager", department_name: "Marketing & Promotion", sector_name: "Marketing", organization_name: "Ministry of Tourism", reporting_to: "Omar Al Sharji", telephone_number: "+971-4-123-4577", mobile_number: "+971-50-123-4577", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae68", ext_no: "2004", name: "Mariam Al Shehhi", email: "mariam.shehhi@tourism.gov", job_title: "Graphics Designer", department_name: "Marketing & Promotion", sector_name: "Marketing", organization_name: "Ministry of Tourism", reporting_to: "Hana Al Qasimi", telephone_number: "+971-4-123-4578", mobile_number: "+971-50-123-4578", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae69", ext_no: "2005", name: "Rashid Al Nuaimi", email: "rashid.nuaimi@tourism.gov", job_title: "Social Media Specialist", department_name: "Marketing & Promotion", sector_name: "Marketing", organization_name: "Ministry of Tourism", reporting_to: "Khalid Al Maktoum", telephone_number: "+971-4-123-4579", mobile_number: "+971-50-123-4579", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae6a", ext_no: "2006", name: "Noor Al Ali", email: "noor.ali@tourism.gov", job_title: "Copywriter", department_name: "Marketing & Promotion", sector_name: "Marketing", organization_name: "Ministry of Tourism", reporting_to: "Hana Al Qasimi", telephone_number: "+971-4-123-4580", mobile_number: "+971-50-123-4580", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae6b", ext_no: "2007", name: "Jamal Al Qassab", email: "jamal.qassab@tourism.gov", job_title: "Video Producer", department_name: "Marketing & Promotion", sector_name: "Marketing", organization_name: "Ministry of Tourism", reporting_to: "Hana Al Qasimi", telephone_number: "+971-4-123-4581", mobile_number: "+971-50-123-4581", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae6c", ext_no: "3001", name: "Lina Al Hajri", email: "lina.hajri@tourism.gov", job_title: "Events Coordinator", department_name: "Events & Hospitality", sector_name: "Hospitality", organization_name: "Ministry of Tourism", reporting_to: "Layla Al Mansouri", telephone_number: "+971-4-123-4582", mobile_number: "+971-50-123-4582", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae6d", ext_no: "3002", name: "Saif Al Mansoori", email: "saif.mansoori@tourism.gov", job_title: "Venue Manager", department_name: "Events & Hospitality", sector_name: "Hospitality", organization_name: "Ministry of Tourism", reporting_to: "Lina Al Hajri", telephone_number: "+971-4-123-4583", mobile_number: "+971-50-123-4583", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae6e", ext_no: "3003", name: "Dina Al Suwaidi", email: "dina.suwaidi@tourism.gov", job_title: "Catering Manager", department_name: "Events & Hospitality", sector_name: "Hospitality", organization_name: "Ministry of Tourism", reporting_to: "Lina Al Hajri", telephone_number: "+971-4-123-4584", mobile_number: "+971-50-123-4584", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae6f", ext_no: "3004", name: "Youssef Al Mualla", email: "youssef.mualla@tourism.gov", job_title: "Logistics Officer", department_name: "Events & Hospitality", sector_name: "Hospitality", organization_name: "Ministry of Tourism", reporting_to: "Saif Al Mansoori", telephone_number: "+971-4-123-4585", mobile_number: "+971-50-123-4585", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae70", ext_no: "3005", name: "Rana Al Dhaheri", email: "rana.dhaheri@tourism.gov", job_title: "Hospitality Specialist", department_name: "Events & Hospitality", sector_name: "Hospitality", organization_name: "Ministry of Tourism", reporting_to: "Dina Al Suwaidi", telephone_number: "+971-4-123-4586", mobile_number: "+971-50-123-4586", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae71", ext_no: "4001", name: "Tariq Al Khatri", email: "tariq.khatri@tourism.gov", job_title: "Heritage Officer", department_name: "Heritage & Culture", sector_name: "Culture", organization_name: "Ministry of Tourism", reporting_to: "Mohammed Al Neyadi", telephone_number: "+971-4-123-4587", mobile_number: "+971-50-123-4587", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae72", ext_no: "4002", name: "Aisha Al Maktoum", email: "aisha.maktoum@tourism.gov", job_title: "Cultural Coordinator", department_name: "Heritage & Culture", sector_name: "Culture", organization_name: "Ministry of Tourism", reporting_to: "Tariq Al Khatri", telephone_number: "+971-4-123-4588", mobile_number: "+971-50-123-4588", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae73", ext_no: "4003", name: "Adel Al Mansoori", email: "adel.mansoori@tourism.gov", job_title: "Museum Director", department_name: "Heritage & Culture", sector_name: "Culture", organization_name: "Ministry of Tourism", reporting_to: "Tariq Al Khatri", telephone_number: "+971-4-123-4589", mobile_number: "+971-50-123-4589", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae74", ext_no: "4004", name: "Zainab Al Qubaisi", email: "zainab.qubaisi@tourism.gov", job_title: "Restoration Specialist", department_name: "Heritage & Culture", sector_name: "Culture", organization_name: "Ministry of Tourism", reporting_to: "Adel Al Mansoori", telephone_number: "+971-4-123-4590", mobile_number: "+971-50-123-4590", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae75", ext_no: "4005", name: "Faisal Al Mansoori", email: "faisal.mansoori@tourism.gov", job_title: "Archaeologist", department_name: "Heritage & Culture", sector_name: "Culture", organization_name: "Ministry of Tourism", reporting_to: "Adel Al Mansoori", telephone_number: "+971-4-123-4591", mobile_number: "+971-50-123-4591", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae76", ext_no: "5001", name: "Mona Al Sheikly", email: "mona.sheikly@tourism.gov", job_title: "Finance Manager", department_name: "Finance & Administration", sector_name: "Administration", organization_name: "Ministry of Tourism", reporting_to: "Fatima Al Khaleej", telephone_number: "+971-4-123-4592", mobile_number: "+971-50-123-4592", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae77", ext_no: "5002", name: "Samir Al Blooshi", email: "samir.blooshi@tourism.gov", job_title: "Accountant", department_name: "Finance & Administration", sector_name: "Administration", organization_name: "Ministry of Tourism", reporting_to: "Mona Al Sheikly", telephone_number: "+971-4-123-4593", mobile_number: "+971-50-123-4593", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae78", ext_no: "5003", name: "Huda Al Qubaisi", email: "huda.qubaisi@tourism.gov", job_title: "Budget Analyst", department_name: "Finance & Administration", sector_name: "Administration", organization_name: "Ministry of Tourism", reporting_to: "Mona Al Sheikly", telephone_number: "+971-4-123-4594", mobile_number: "+971-50-123-4594", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae79", ext_no: "5004", name: "Waleed Al Ketbi", email: "waleed.ketbi@tourism.gov", job_title: "HR Manager", department_name: "Finance & Administration", sector_name: "Administration", organization_name: "Ministry of Tourism", reporting_to: "Mona Al Sheikly", telephone_number: "+971-4-123-4595", mobile_number: "+971-50-123-4595", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae7a", ext_no: "5005", name: "Leila Al Naqbi", email: "leila.naqbi@tourism.gov", job_title: "Recruitment Officer", department_name: "Finance & Administration", sector_name: "Administration", organization_name: "Ministry of Tourism", reporting_to: "Waleed Al Ketbi", telephone_number: "+971-4-123-4596", mobile_number: "+971-50-123-4596", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae7b", ext_no: "6001", name: "Karim Al Mansoori", email: "karim.mansoori@tourism.gov", job_title: "IT Director", department_name: "Information Technology", sector_name: "Technology", organization_name: "Ministry of Tourism", reporting_to: "Fatima Al Khaleej", telephone_number: "+971-4-123-4597", mobile_number: "+971-50-123-4597", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae7c", ext_no: "6002", name: "Amal Al Rawahi", email: "amal.rawahi@tourism.gov", job_title: "Systems Administrator", department_name: "Information Technology", sector_name: "Technology", organization_name: "Ministry of Tourism", reporting_to: "Karim Al Mansoori", telephone_number: "+971-4-123-4598", mobile_number: "+971-50-123-4598", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae7d", ext_no: "6003", name: "Bilal Al Zaabi", email: "bilal.zaabi@tourism.gov", job_title: "Database Manager", department_name: "Information Technology", sector_name: "Technology", organization_name: "Ministry of Tourism", reporting_to: "Karim Al Mansoori", telephone_number: "+971-4-123-4599", mobile_number: "+971-50-123-4599", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae7e", ext_no: "6004", name: "Nadia Al Kaabi", email: "nadia.kaabi@tourism.gov", job_title: "Software Developer", department_name: "Information Technology", sector_name: "Technology", organization_name: "Ministry of Tourism", reporting_to: "Karim Al Mansoori", telephone_number: "+971-4-123-4600", mobile_number: "+971-50-123-4600", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae7f", ext_no: "6005", name: "Rami Al Hashmi", email: "rami.hashmi@tourism.gov", job_title: "Network Engineer", department_name: "Information Technology", sector_name: "Technology", organization_name: "Ministry of Tourism", reporting_to: "Karim Al Mansoori", telephone_number: "+971-4-123-4601", mobile_number: "+971-50-123-4601", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae80", ext_no: "6006", name: "Samira Al Suwaidi", email: "samira.suwaidi@tourism.gov", job_title: "IT Support Officer", department_name: "Information Technology", sector_name: "Technology", organization_name: "Ministry of Tourism", reporting_to: "Amal Al Rawahi", telephone_number: "+971-4-123-4602", mobile_number: "+971-50-123-4602", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae81", ext_no: "6007", name: "Hamza Al Mansoori", email: "hamza.mansoori@tourism.gov", job_title: "Web Developer", department_name: "Information Technology", sector_name: "Technology", organization_name: "Ministry of Tourism", reporting_to: "Nadia Al Kaabi", telephone_number: "+971-4-123-4603", mobile_number: "+971-50-123-4603", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae82", ext_no: "7001", name: "Rania Al Qubaisi", email: "rania.qubaisi@tourism.gov", job_title: "Legal Advisor", department_name: "Legal & Compliance", sector_name: "Legal", organization_name: "Ministry of Tourism", reporting_to: "Ahmed Al Mansouri", telephone_number: "+971-4-123-4604", mobile_number: "+971-50-123-4604", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae83", ext_no: "7002", name: "Hani Al Menhali", email: "hani.menhali@tourism.gov", job_title: "Compliance Officer", department_name: "Legal & Compliance", sector_name: "Legal", organization_name: "Ministry of Tourism", reporting_to: "Rania Al Qubaisi", telephone_number: "+971-4-123-4605", mobile_number: "+971-50-123-4605", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae84", ext_no: "7003", name: "Diana Al Ketbi", email: "diana.ketbi@tourism.gov", job_title: "Contracts Specialist", department_name: "Legal & Compliance", sector_name: "Legal", organization_name: "Ministry of Tourism", reporting_to: "Rania Al Qubaisi", telephone_number: "+971-4-123-4606", mobile_number: "+971-50-123-4606", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae85", ext_no: "8001", name: "Sohail Al Mansoori", email: "sohail.mansoori@tourism.gov", job_title: "Public Relations Manager", department_name: "Communications", sector_name: "Communications", organization_name: "Ministry of Tourism", reporting_to: "Mohammed Al Neyadi", telephone_number: "+971-4-123-4607", mobile_number: "+971-50-123-4607", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae86", ext_no: "8002", name: "Hiba Al Suwaidi", email: "hiba.suwaidi@tourism.gov", job_title: "Media Officer", department_name: "Communications", sector_name: "Communications", organization_name: "Ministry of Tourism", reporting_to: "Sohail Al Mansoori", telephone_number: "+971-4-123-4608", mobile_number: "+971-50-123-4608", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae87", ext_no: "8003", name: "Yaseen Al Mansoori", email: "yaseen.mansoori@tourism.gov", job_title: "Press Officer", department_name: "Communications", sector_name: "Communications", organization_name: "Ministry of Tourism", reporting_to: "Sohail Al Mansoori", telephone_number: "+971-4-123-4609", mobile_number: "+971-50-123-4609", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae88", ext_no: "8004", name: "Jasmine Al Qasimi", email: "jasmine.qasimi@tourism.gov", job_title: "Communications Specialist", department_name: "Communications", sector_name: "Communications", organization_name: "Ministry of Tourism", reporting_to: "Hiba Al Suwaidi", telephone_number: "+971-4-123-4610", mobile_number: "+971-50-123-4610", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae89", ext_no: "9001", name: "Mehdi Al Alawi", email: "mehdi.alawi@tourism.gov", job_title: "Training Coordinator", department_name: "Human Development", sector_name: "Training", organization_name: "Ministry of Tourism", reporting_to: "Waleed Al Ketbi", telephone_number: "+971-4-123-4611", mobile_number: "+971-50-123-4611", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae8a", ext_no: "9002", name: "Reem Al Blooshi", email: "reem.blooshi@tourism.gov", job_title: "Training Specialist", department_name: "Human Development", sector_name: "Training", organization_name: "Ministry of Tourism", reporting_to: "Mehdi Al Alawi", telephone_number: "+971-4-123-4612", mobile_number: "+971-50-123-4612", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae8b", ext_no: "9003", name: "Mazen Al Mansoori", email: "mazen.mansoori@tourism.gov", job_title: "Development Officer", department_name: "Human Development", sector_name: "Training", organization_name: "Ministry of Tourism", reporting_to: "Mehdi Al Alawi", telephone_number: "+971-4-123-4613", mobile_number: "+971-50-123-4613", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae8c", ext_no: "10001", name: "Suzy Al Mazrouei", email: "suzy.mazrouei@tourism.gov", job_title: "Quality Assurance Manager", department_name: "Quality & Standards", sector_name: "Quality", organization_name: "Ministry of Tourism", reporting_to: "Mohammed Al Neyadi", telephone_number: "+971-4-123-4614", mobile_number: "+971-50-123-4614", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae8d", ext_no: "10002", name: "Nizar Al Mansoori", email: "nizar.mansoori@tourism.gov", job_title: "QA Specialist", department_name: "Quality & Standards", sector_name: "Quality", organization_name: "Ministry of Tourism", reporting_to: "Suzy Al Mazrouei", telephone_number: "+971-4-123-4615", mobile_number: "+971-50-123-4615", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae8e", ext_no: "10003", name: "Maryam Al Rawahi", email: "maryam.rawahi@tourism.gov", job_title: "Standards Officer", department_name: "Quality & Standards", sector_name: "Quality", organization_name: "Ministry of Tourism", reporting_to: "Suzy Al Mazrouei", telephone_number: "+971-4-123-4616", mobile_number: "+971-50-123-4616", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae8f", ext_no: "11001", name: "Hassan Al Mansoori", email: "hassan.mansoori@tourism.gov", job_title: "Research Manager", department_name: "Research & Analytics", sector_name: "Research", organization_name: "Ministry of Tourism", reporting_to: "Mohammed Al Neyadi", telephone_number: "+971-4-123-4617", mobile_number: "+971-50-123-4617", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae90", ext_no: "11002", name: "Fatma Al Khaleej", email: "fatma.khaleej@tourism.gov", job_title: "Data Analyst", department_name: "Research & Analytics", sector_name: "Research", organization_name: "Ministry of Tourism", reporting_to: "Hassan Al Mansoori", telephone_number: "+971-4-123-4618", mobile_number: "+971-50-123-4618", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae91", ext_no: "11003", name: "Sami Al Mansoori", email: "sami.mansoori@tourism.gov", job_title: "Research Officer", department_name: "Research & Analytics", sector_name: "Research", organization_name: "Ministry of Tourism", reporting_to: "Hassan Al Mansoori", telephone_number: "+971-4-123-4619", mobile_number: "+971-50-123-4619", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae92", ext_no: "11004", name: "Laila Al Naqbi", email: "laila.naqbi@tourism.gov", job_title: "Market Research Specialist", department_name: "Research & Analytics", sector_name: "Research", organization_name: "Ministry of Tourism", reporting_to: "Hassan Al Mansoori", telephone_number: "+971-4-123-4620", mobile_number: "+971-50-123-4620", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae93", ext_no: "12001", name: "Tariq Al Mansoori", email: "tariq.mansoori@tourism.gov", job_title: "Sustainability Coordinator", department_name: "Sustainability", sector_name: "Environment", organization_name: "Ministry of Tourism", reporting_to: "Mohammed Al Neyadi", telephone_number: "+971-4-123-4621", mobile_number: "+971-50-123-4621", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae94", ext_no: "12002", name: "Yasmin Al Kaabi", email: "yasmin.kaabi@tourism.gov", job_title: "Environmental Specialist", department_name: "Sustainability", sector_name: "Environment", organization_name: "Ministry of Tourism", reporting_to: "Tariq Al Mansoori", telephone_number: "+971-4-123-4622", mobile_number: "+971-50-123-4622", created_date: "2026-02-17T15:18:39.883Z" },
    { id: "699486cf6860a0380869ae95", ext_no: "12003", name: "Amr Al Mansoori", email: "amr.mansoori@tourism.gov", job_title: "Green Projects Officer", department_name: "Sustainability", sector_name: "Environment", organization_name: "Ministry of Tourism", reporting_to: "Tariq Al Mansoori", telephone_number: "+971-4-123-4623", mobile_number: "+971-50-123-4623", created_date: "2026-02-17T15:18:39.883Z" },
  ];

  // Real Initiatives from Base44 export
  const initiatives = [
    { id: "69968d421fdeeacc4c795dfc", pillar: "Smart City Digital Infrastructure", brief_description: "Deploy city-wide IoT sensors and connectivity backbone for smart city services", deliverables: "IoT network deployment, data dashboard, connectivity report", lead_user_id: "user1", lead_user_name: "Ahmed Al-Mansouri", support_users: ["user2"], support_user_names: ["Fatima Al-Kitbi"], start_date: "2026-01-05", due_date: "2026-06-30", status: "in_progress", completion_percent: 45, priority: "high", stakeholders: ["IT Department", "Municipality", "Etisalat"], dependencies: "", notes: "Fiber optic backbone installation underway in Phase 1 zones", tags: ["smart-city", "IoT", "infrastructure"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795dfd", pillar: "E-Government Services Portal", brief_description: "Unified online portal for all government services to improve citizen experience", deliverables: "Web portal, mobile app, service catalog, API integrations", lead_user_id: "user2", lead_user_name: "Fatima Al-Kitbi", support_users: ["user3"], support_user_names: ["Mohammed Al-Zahrani"], start_date: "2026-01-15", due_date: "2026-05-31", status: "in_progress", completion_percent: 60, priority: "urgent", stakeholders: ["All Departments", "Ministry of Digital Economy"], dependencies: "", notes: "UAT phase starts next week with pilot departments", tags: ["e-government", "portal", "digital"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795dfe", pillar: "Public Health Awareness Campaign", brief_description: "Nationwide campaign promoting preventive health measures and wellness programs", deliverables: "Campaign materials, social media content, community events, health kiosks", lead_user_id: "user3", lead_user_name: "Mohammed Al-Zahrani", support_users: ["user1"], support_user_names: ["Ahmed Al-Mansouri"], start_date: "2026-02-01", due_date: "2026-04-30", status: "in_progress", completion_percent: 55, priority: "high", stakeholders: ["Health Department", "Media Office", "NGOs"], dependencies: "", notes: "Phase 1 rollout in 5 districts completed successfully", tags: ["health", "awareness", "campaign"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795dff", pillar: "Education Technology Integration", brief_description: "Integrate AI-powered learning tools across all public schools and universities", deliverables: "LMS platform, teacher training, device rollout, curriculum content", lead_user_id: "user1", lead_user_name: "Ahmed Al-Mansouri", support_users: ["user2", "user3"], support_user_names: ["Fatima Al-Kitbi", "Mohammed Al-Zahrani"], start_date: "2026-01-20", due_date: "2026-07-31", status: "in_progress", completion_percent: 30, priority: "high", stakeholders: ["Ministry of Education", "Schools", "Tech Vendors"], dependencies: "", notes: "Procurement of 10,000 tablets completed; software deployment next", tags: ["education", "technology", "AI"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795e00", pillar: "Water Conservation & Management", brief_description: "Implement smart water management systems to reduce consumption by 30%", deliverables: "Smart meters, leak detection system, conservation guidelines, public report", lead_user_id: "user2", lead_user_name: "Fatima Al-Kitbi", support_users: [], support_user_names: [], start_date: "2026-02-10", due_date: "2026-08-31", status: "not_started", completion_percent: 0, priority: "medium", stakeholders: ["Environment Agency", "Utilities", "Residents"], dependencies: "", notes: "Budget approved; RFP to be issued next month", tags: ["environment", "water", "sustainability"], workflow_stage_id: "", is_archived: false, requires_approval: true, approval_status: "submitted", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795e01", pillar: "Road Safety & Traffic Management", brief_description: "Deploy intelligent traffic management systems and reduce accident rates by 25%", deliverables: "Traffic cameras, AI analytics, smart signals, incident response protocol", lead_user_id: "user3", lead_user_name: "Mohammed Al-Zahrani", support_users: ["user1"], support_user_names: ["Ahmed Al-Mansouri"], start_date: "2026-01-10", due_date: "2026-09-30", status: "in_progress", completion_percent: 40, priority: "urgent", stakeholders: ["Police Department", "Roads Authority", "Municipality"], dependencies: "", notes: "150 smart cameras installed; AI training model in calibration", tags: ["traffic", "safety", "smart-city"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795e02", pillar: "Youth Entrepreneurship Program", brief_description: "Launch incubator and mentorship programs to support young entrepreneurs aged 18-35", deliverables: "Incubator space, mentorship network, funding framework, 50 startups supported", lead_user_id: "user1", lead_user_name: "Ahmed Al-Mansouri", support_users: ["user2"], support_user_names: ["Fatima Al-Kitbi"], start_date: "2026-02-15", due_date: "2026-12-31", status: "in_progress", completion_percent: 20, priority: "medium", stakeholders: ["Economic Department", "Banks", "Universities"], dependencies: "", notes: "First cohort of 30 startups selected for Q2 intake", tags: ["youth", "entrepreneurship", "innovation"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795e03", pillar: "Renewable Energy Transition", brief_description: "Transition 40% of government buildings to solar energy by end of year", deliverables: "Solar panel installations, energy audit reports, ROI analysis, green certification", lead_user_id: "user2", lead_user_name: "Fatima Al-Kitbi", support_users: ["user3"], support_user_names: ["Mohammed Al-Zahrani"], start_date: "2026-01-01", due_date: "2026-12-31", status: "in_progress", completion_percent: 25, priority: "high", stakeholders: ["Ministry of Energy", "DEWA", "Contractors"], dependencies: "", notes: "10 buildings completed; 35 more in procurement stage", tags: ["renewable", "solar", "environment"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795e04", pillar: "Cybersecurity Framework Enhancement", brief_description: "Strengthen government cybersecurity posture with zero-trust architecture", deliverables: "Security audit, zero-trust implementation, staff training, incident response plan", lead_user_id: "user3", lead_user_name: "Mohammed Al-Zahrani", support_users: ["user1", "user2"], support_user_names: ["Ahmed Al-Mansouri", "Fatima Al-Kitbi"], start_date: "2026-01-15", due_date: "2026-06-30", status: "in_progress", completion_percent: 50, priority: "urgent", stakeholders: ["IT Department", "All Ministries", "NESA"], dependencies: "", notes: "Phase 1 audit complete; critical vulnerabilities addressed", tags: ["cybersecurity", "IT", "zero-trust"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795e05", pillar: "Public Transport Expansion", brief_description: "Expand bus and metro coverage to underserved areas; add 15 new routes", deliverables: "15 new routes, bus procurement, route maps, digital ticketing system", lead_user_id: "user1", lead_user_name: "Ahmed Al-Mansouri", support_users: [], support_user_names: [], start_date: "2026-02-01", due_date: "2026-10-31", status: "not_started", completion_percent: 0, priority: "high", stakeholders: ["RTA", "Municipalities", "Residents"], dependencies: "", notes: "Awaiting final budget approval from cabinet", tags: ["transport", "public-services", "infrastructure"], workflow_stage_id: "", is_archived: false, requires_approval: true, approval_status: "submitted", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795e06", pillar: "Social Welfare Benefits Digitalization", brief_description: "Digitize social welfare applications and disbursement to reduce processing time by 70%", deliverables: "Digital application system, automated eligibility check, mobile disbursement", lead_user_id: "user2", lead_user_name: "Fatima Al-Kitbi", support_users: ["user3"], support_user_names: ["Mohammed Al-Zahrani"], start_date: "2026-01-20", due_date: "2026-05-31", status: "in_progress", completion_percent: 65, priority: "urgent", stakeholders: ["Ministry of Community", "Banks", "Beneficiaries"], dependencies: "", notes: "Pilot with 500 beneficiaries showing 68% processing time reduction", tags: ["social-welfare", "digitalization", "government"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795e07", pillar: "Green Building Standards Rollout", brief_description: "Enforce new green building codes for all new construction projects citywide", deliverables: "Updated building code, inspector training, compliance portal, 100 certified buildings", lead_user_id: "user3", lead_user_name: "Mohammed Al-Zahrani", support_users: ["user1"], support_user_names: ["Ahmed Al-Mansouri"], start_date: "2026-02-01", due_date: "2026-07-31", status: "in_progress", completion_percent: 35, priority: "medium", stakeholders: ["Municipalities", "Developers", "Environment Agency"], dependencies: "", notes: "Training program for 200 building inspectors launched", tags: ["green", "construction", "sustainability"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795e08", pillar: "Sports & Recreation Facilities Development", brief_description: "Construct 20 new community sports centers and upgrade existing parks", deliverables: "20 sports centers, park upgrades, fitness programs, community engagement report", lead_user_id: "user1", lead_user_name: "Ahmed Al-Mansouri", support_users: ["user2"], support_user_names: ["Fatima Al-Kitbi"], start_date: "2026-01-15", due_date: "2026-11-30", status: "in_progress", completion_percent: 15, priority: "medium", stakeholders: ["Sports Council", "Municipality", "Communities"], dependencies: "", notes: "Land allocation for 20 sites confirmed; architectural designs underway", tags: ["sports", "recreation", "community"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795e09", pillar: "Food Safety & Inspection Modernization", brief_description: "Modernize food safety inspection processes using mobile tools and AI risk scoring", deliverables: "Mobile inspection app, AI risk model, inspector training, compliance reports", lead_user_id: "user2", lead_user_name: "Fatima Al-Kitbi", support_users: [], support_user_names: [], start_date: "2026-02-10", due_date: "2026-06-30", status: "in_progress", completion_percent: 50, priority: "high", stakeholders: ["Health Department", "Restaurants", "Food Suppliers"], dependencies: "", notes: "Mobile app in beta testing with 30 inspectors; feedback positive", tags: ["food-safety", "inspection", "health"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795e0a", pillar: "Housing Affordability Initiative", brief_description: "Develop 5,000 affordable housing units for mid and low-income families", deliverables: "5,000 housing units, financing schemes, community facilities, handover process", lead_user_id: "user3", lead_user_name: "Mohammed Al-Zahrani", support_users: ["user1", "user2"], support_user_names: ["Ahmed Al-Mansouri", "Fatima Al-Kitbi"], start_date: "2026-01-01", due_date: "2027-06-30", status: "in_progress", completion_percent: 10, priority: "urgent", stakeholders: ["Housing Authority", "Developers", "Banks", "Families"], dependencies: "", notes: "Construction permits for Phase 1 (1,500 units) issued", tags: ["housing", "community", "development"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795e0b", pillar: "Digital Identity & eKYC System", brief_description: "Launch national digital identity system enabling seamless eKYC for all services", deliverables: "Digital ID infrastructure, biometric integration, API for 50+ services", lead_user_id: "user1", lead_user_name: "Ahmed Al-Mansouri", support_users: ["user3"], support_user_names: ["Mohammed Al-Zahrani"], start_date: "2026-01-10", due_date: "2026-08-31", status: "in_progress", completion_percent: 55, priority: "urgent", stakeholders: ["Ministry of Interior", "Banks", "All Departments"], dependencies: "", notes: "Biometric enrollment of 1.2M residents completed; system integration ongoing", tags: ["digital-identity", "eKYC", "security"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.653Z" },
    { id: "69968d421fdeeacc4c795e0c", pillar: "Economic Free Zone Expansion", brief_description: "Expand free zone capacity with new facilities to attract 500 new businesses", deliverables: "New office buildings, streamlined licensing, investor roadshow, 500 new licenses", lead_user_id: "user2", lead_user_name: "Fatima Al-Kitbi", support_users: ["user1"], support_user_names: ["Ahmed Al-Mansouri"], start_date: "2026-02-01", due_date: "2026-12-31", status: "in_progress", completion_percent: 20, priority: "high", stakeholders: ["Economic Department", "Investors", "Contractors"], dependencies: "", notes: "Phase 1 construction of 3 commercial towers started", tags: ["economy", "free-zone", "investment"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.654Z" },
    { id: "69968d421fdeeacc4c795e10", pillar: "AI-Powered Government Analytics Platform", brief_description: "Deploy a centralized AI analytics platform for data-driven government decision making", deliverables: "Analytics platform, 50 dashboards, AI models, training for 200 staff", lead_user_id: "user3", lead_user_name: "Mohammed Al-Zahrani", support_users: ["user1", "user2"], support_user_names: ["Ahmed Al-Mansouri", "Fatima Al-Kitbi"], start_date: "2026-01-15", due_date: "2026-10-31", status: "in_progress", completion_percent: 35, priority: "high", stakeholders: ["All Ministries", "Statistics Center", "Tech Partners"], dependencies: "", notes: "Platform architecture finalized; data ingestion pipelines being built", tags: ["AI", "analytics", "data"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.654Z" },
    { id: "69968d421fdeeacc4c795e11", pillar: "Port Logistics Efficiency Upgrade", brief_description: "Modernize port operations with blockchain-based tracking and automated customs clearance", deliverables: "Blockchain cargo tracking, automated customs, digital manifests, SLA reduction to 4hrs", lead_user_id: "user1", lead_user_name: "Ahmed Al-Mansouri", support_users: ["user2"], support_user_names: ["Fatima Al-Kitbi"], start_date: "2026-01-05", due_date: "2026-09-30", status: "in_progress", completion_percent: 45, priority: "urgent", stakeholders: ["Port Authority", "Customs", "Shipping Lines"], dependencies: "", notes: "Blockchain pilot running on 200 containers per week; expanding to full capacity", tags: ["port", "logistics", "blockchain"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.654Z" },
    { id: "69968d421fdeeacc4c795e12", pillar: "Mental Health Support Services", brief_description: "Launch city-wide mental health awareness and counseling support programs", deliverables: "24/7 hotline, 10 counseling centers, awareness campaign, school programs", lead_user_id: "user2", lead_user_name: "Fatima Al-Kitbi", support_users: [], support_user_names: [], start_date: "2026-02-10", due_date: "2026-06-30", status: "in_progress", completion_percent: 60, priority: "high", stakeholders: ["Health Department", "Schools", "NGOs"], dependencies: "", notes: "Hotline operational; 3,000 calls handled in first two months", tags: ["mental-health", "health", "community"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.654Z" },
    { id: "69968d421fdeeacc4c795e15", pillar: "Emergency Response System Modernization", brief_description: "Upgrade emergency dispatch systems with AI-assisted call routing and resource allocation", deliverables: "AI dispatch system, mobile unit app, real-time tracking, response time under 5 mins", lead_user_id: "user2", lead_user_name: "Fatima Al-Kitbi", support_users: ["user3"], support_user_names: ["Mohammed Al-Zahrani"], start_date: "2026-01-10", due_date: "2026-07-31", status: "in_progress", completion_percent: 70, priority: "urgent", stakeholders: ["Civil Defense", "Police", "Health Authority"], dependencies: "", notes: "AI model achieving 94% accuracy in call classification; going live in April", tags: ["emergency", "AI", "public-safety"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.654Z" },
    { id: "69968d421fdeeacc4c795e18", pillar: "Flood Risk Management System", brief_description: "Install early warning flood detection and real-time drainage monitoring across the city", deliverables: "200 flood sensors, early warning SMS system, drainage upgrade plan, response playbook", lead_user_id: "user2", lead_user_name: "Fatima Al-Kitbi", support_users: [], support_user_names: [], start_date: "2026-01-15", due_date: "2026-05-31", status: "completed", completion_percent: 100, priority: "urgent", stakeholders: ["Civil Defense", "Municipality", "Utilities"], dependencies: "", notes: "All sensors installed; system tested successfully in January rains", tags: ["flood", "infrastructure", "emergency"], workflow_stage_id: "6993579cad61306bbed982b9", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.654Z" },
    { id: "69968d421fdeeacc4c795e1b", pillar: "Business Licensing Process Reengineering", brief_description: "Reduce business license issuance time from 5 days to 1 hour through full digitalization", deliverables: "Automated licensing portal, API integrations, SLA framework, 1-hour license issuance", lead_user_id: "user2", lead_user_name: "Fatima Al-Kitbi", support_users: ["user3"], support_user_names: ["Mohammed Al-Zahrani"], start_date: "2026-01-10", due_date: "2026-04-30", status: "in_progress", completion_percent: 75, priority: "urgent", stakeholders: ["Economic Department", "Businesses", "All Agencies"], dependencies: "", notes: "95% of license types now automated; average processing time down to 1.5 hours", tags: ["business", "licensing", "e-services"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "approved", created_date: "2026-02-19T04:10:42.654Z" },
    { id: "699346bd705fa209705e5abb", pillar: "Tourism Infrastructure Development", brief_description: "Develop modern tourism infrastructure across key destinations", deliverables: "Infrastructure plans and feasibility reports", lead_user_id: "user1", lead_user_name: "Ahmed Al-Mansouri", support_users: [], support_user_names: [], start_date: "2026-01-15", due_date: "2026-02-28", status: "completed", completion_percent: 100, priority: "high", stakeholders: [], dependencies: "", notes: "Waiting for stakeholder approval on design specs", tags: ["infrastructure", "development"], workflow_stage_id: "", is_archived: false, requires_approval: false, approval_status: "draft", created_date: "2026-02-16T16:33:01.212Z" },
    { id: "699346bd705fa209705e5abc", pillar: "Digital Marketing Campaign", brief_description: "Launch comprehensive digital marketing to boost tourism", deliverables: "Marketing materials, social media content, ad campaigns", lead_user_id: "user2", lead_user_name: "Fatima Al-Kitbi", support_users: ["user3"], support_user_names: ["Mohammed Al-Zahrani"], start_date: "2026-02-01", due_date: "2026-02-20", status: "completed", completion_percent: 100, priority: "urgent", stakeholders: [], dependencies: "", notes: "", tags: ["marketing", "digital"], workflow_stage_id: "", is_archived: false, requires_approval: false, approval_status: "draft", created_date: "2026-02-16T16:33:01.212Z" },
    { id: "699346bd705fa209705e5abd", pillar: "Hotel Classification System", brief_description: "Implement new star-rating hotel classification", deliverables: "Classification criteria, training materials", lead_user_id: "user3", lead_user_name: "Mohammed Al-Zahrani", support_users: [], support_user_names: [], start_date: "2026-02-10", due_date: "2026-03-15", status: "completed", completion_percent: 100, priority: "medium", stakeholders: [], dependencies: "", notes: "", tags: ["hotels", "classification"], workflow_stage_id: "", is_archived: false, requires_approval: false, approval_status: "draft", created_date: "2026-02-16T16:33:01.212Z" },
    { id: "699346bd705fa209705e5abe", pillar: "Cultural Heritage Preservation", brief_description: "Preserve and promote cultural heritage sites", deliverables: "Heritage documentation, preservation plans", lead_user_id: "user1", lead_user_name: "Ahmed Al-Mansouri", support_users: [], support_user_names: [], start_date: "2026-01-20", due_date: "2026-02-10", status: "delayed", completion_percent: 25, priority: "high", stakeholders: [], dependencies: "", notes: "Delayed due to permit delays from municipal authorities", tags: ["heritage", "culture"], workflow_stage_id: "", is_archived: false, requires_approval: false, approval_status: "draft", created_date: "2026-02-16T16:33:01.212Z" },
    { id: "699346bd705fa209705e5abf", pillar: "Tourist Guide Training Program", brief_description: "Comprehensive training for professional tour guides", deliverables: "Training curriculum, certification programs", lead_user_id: "user2", lead_user_name: "Fatima Al-Kitbi", support_users: ["user1", "user3"], support_user_names: ["Ahmed Al-Mansouri", "Mohammed Al-Zahrani"], start_date: "2026-02-05", due_date: "2026-02-25", status: "in_progress", completion_percent: 70, priority: "medium", stakeholders: [], dependencies: "", notes: "", tags: ["training", "guides"], workflow_stage_id: "", is_archived: false, requires_approval: false, approval_status: "draft", created_date: "2026-02-16T16:33:01.212Z" },
    { id: "699346bd705fa209705e5ac0", pillar: "Event Management Platform", brief_description: "Build digital platform for tourism events", deliverables: "Web platform, mobile app integration", lead_user_id: "user3", lead_user_name: "Mohammed Al-Zahrani", support_users: [], support_user_names: [], start_date: "2026-01-10", due_date: "2026-01-31", status: "completed", completion_percent: 100, priority: "high", stakeholders: [], dependencies: "", notes: "", tags: ["events", "digital", "platform"], workflow_stage_id: "6993579cad61306bbed982b7", is_archived: false, requires_approval: false, approval_status: "draft", created_date: "2026-02-16T16:33:01.212Z" },
    { id: "699346bd705fa209705e5ac1", pillar: "Sustainable Tourism Initiative", brief_description: "Implement eco-friendly tourism practices", deliverables: "Sustainability guidelines, green certification programs", lead_user_id: "user1", lead_user_name: "Ahmed Al-Mansouri", support_users: [], support_user_names: [], start_date: "2026-02-15", due_date: "2026-03-30", status: "not_started", completion_percent: 0, priority: "medium", stakeholders: [], dependencies: "", notes: "", tags: ["sustainability", "environment"], workflow_stage_id: "", is_archived: false, requires_approval: false, approval_status: "draft", created_date: "2026-02-16T16:33:01.212Z" },
    { id: "699346bd705fa209705e5ac2", pillar: "International Partnership Agreements", brief_description: "Establish partnerships with international tourism boards", deliverables: "Partnership MOUs, collaboration frameworks", lead_user_id: "user2", lead_user_name: "Fatima Al-Kitbi", support_users: ["user1"], support_user_names: ["Ahmed Al-Mansouri"], start_date: "2026-02-01", due_date: "2026-02-28", status: "in_progress", completion_percent: 35, priority: "high", stakeholders: [], dependencies: "", notes: "Negotiating terms with 3 international partners", tags: ["partnerships", "international"], workflow_stage_id: "", is_archived: false, requires_approval: false, approval_status: "draft", created_date: "2026-02-16T16:33:01.212Z" },
    { id: "699346bd705fa209705e5ac4", pillar: "Tourism Revenue Analysis Report", brief_description: "Quarterly analysis of tourism revenue trends", deliverables: "Detailed financial reports with forecasts", lead_user_id: "user1", lead_user_name: "Ahmed Al-Mansouri", support_users: [], support_user_names: [], start_date: "2026-02-10", due_date: "2026-02-18", status: "in_progress", completion_percent: 80, priority: "medium", stakeholders: [], dependencies: "", notes: "", tags: ["analytics", "finance", "reporting"], workflow_stage_id: "", is_archived: false, requires_approval: false, approval_status: "draft", created_date: "2026-02-16T16:33:01.212Z" },
  ];

  // Real Email Messages from Base44 export
  const emailMessages = [
    { id: "69968e1f9507b606e2e2da89", subject: "Invitation: Annual Government Digital Transformation Summit 2026", from_name: "World Economic Forum", from_email: "partnerships@weforum.org", to_emails: ["gov@department.gov"], cc_emails: ["director@department.gov"], body_preview: "The World Economic Forum is pleased to invite your department to participate in the Annual Government Digital Transformation Summit scheduled for April 2026 in Davos. We believe your insights on AI-powered governance will greatly enrich discussions.", body_text: "The World Economic Forum is pleased to invite your department to participate in the Annual Government Digital Transformation Summit scheduled for April 2026 in Davos. We believe your insights on AI-powered governance will greatly enrich discussions.", received_at: "2026-02-18T09:15:00Z", status_in_system: "new", mailbox: "", is_read: false, is_starred: true, category: "invitation", suggested_category: "invitation", suggested_priority: "urgent", has_attachments: true, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-02-19T04:14:23.939Z" },
    { id: "69968e1f9507b606e2e2da8a", subject: "Project Delay Notice – IoT Sensor Installation Phase 2", from_name: "Khalid Al-Hamdan", from_email: "khalid.h@smartcity-contractor.com", to_emails: ["projects@department.gov"], cc_emails: [], body_preview: "We regret to inform you that Phase 2 of the IoT sensor installation project will be delayed by approximately 3 weeks due to supply chain disruptions affecting sensor modules from our primary vendor in South Korea.", body_text: "We regret to inform you that Phase 2 of the IoT sensor installation project will be delayed by approximately 3 weeks due to supply chain disruptions affecting sensor modules from our primary vendor in South Korea.", received_at: "2026-02-17T11:40:00Z", status_in_system: "new", mailbox: "", is_read: true, is_starred: false, category: "complaint", suggested_category: "complaint", suggested_priority: "high", has_attachments: true, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-02-19T04:14:23.939Z" },
    { id: "69968e1f9507b606e2e2da8b", subject: "Request: Public Health Campaign Data Collaboration", from_name: "Dr. Aisha Al-Nouri", from_email: "a.nouri@healthauthority.gov", to_emails: ["gov@department.gov"], cc_emails: ["data@healthauthority.gov"], body_preview: "Dear Team, we are reaching out to request data collaboration for the upcoming Public Health Awareness Campaign. We need access to demographic datasets for Q1 2026 to better target our outreach efforts in underserved communities.", body_text: "Dear Team, we are reaching out to request data collaboration for the upcoming Public Health Awareness Campaign. We need access to demographic datasets for Q1 2026 to better target our outreach efforts in underserved communities.", received_at: "2026-02-17T08:00:00Z", status_in_system: "triaged", mailbox: "", is_read: true, is_starred: false, category: "data_request", suggested_category: "data_request", suggested_priority: "medium", has_attachments: false, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-02-19T04:14:23.939Z" },
    { id: "69968e1f9507b606e2e2da8c", subject: "Press Inquiry – Government AI Analytics Platform Launch", from_name: "Reuters Media Group", from_email: "press@reuters.com", to_emails: ["media@department.gov"], cc_emails: [], body_preview: "Reuters is covering the launch of government AI platforms across the Gulf region. We would like to request a spokesperson from your department for a 20-minute interview to discuss the AI-Powered Government Analytics Platform initiative.", body_text: "Reuters is covering the launch of government AI platforms across the Gulf region. We would like to request a spokesperson from your department for a 20-minute interview to discuss the AI-Powered Government Analytics Platform initiative.", received_at: "2026-02-16T14:30:00Z", status_in_system: "new", mailbox: "", is_read: true, is_starred: false, category: "media", suggested_category: "media", suggested_priority: "high", has_attachments: false, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-02-19T04:14:23.939Z" },
    { id: "69968e1f9507b606e2e2da8d", subject: "MoU Proposal – Smart City Technology Knowledge Exchange", from_name: "Singapore Smart Nation Office", from_email: "partnership@smartnation.gov.sg", to_emails: ["international@department.gov"], cc_emails: [], body_preview: "The Singapore Smart Nation and Digital Government Office wishes to propose a Memorandum of Understanding for bilateral knowledge exchange in smart city technologies, digital identity systems, and AI governance frameworks.", body_text: "The Singapore Smart Nation and Digital Government Office wishes to propose a Memorandum of Understanding for bilateral knowledge exchange in smart city technologies, digital identity systems, and AI governance frameworks.", received_at: "2026-02-15T06:45:00Z", status_in_system: "triaged", mailbox: "", is_read: true, is_starred: true, category: "mou", suggested_category: "mou", suggested_priority: "high", has_attachments: true, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-02-19T04:14:23.939Z" },
    { id: "69968e1f9507b606e2e2da8e", subject: "Complaint: Road Safety Issue Near School Zone – District 7", from_name: "Fatima Saeed Al-Bloushi", from_email: "f.bloushi@resident.ae", to_emails: ["complaints@department.gov"], cc_emails: [], body_preview: "I am writing on behalf of concerned parents in District 7 regarding the dangerous traffic conditions near Al Noor Primary School. Despite multiple reports, no traffic signals or speed bumps have been installed.", body_text: "I am writing on behalf of concerned parents in District 7 regarding the dangerous traffic conditions near Al Noor Primary School. Despite multiple reports, no traffic signals or speed bumps have been installed.", received_at: "2026-02-15T10:20:00Z", status_in_system: "new", mailbox: "", is_read: true, is_starred: false, category: "complaint", suggested_category: "complaint", suggested_priority: "urgent", has_attachments: false, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-02-19T04:14:23.939Z" },
    { id: "69968e1f9507b606e2e2da8f", subject: "Annual Economic Data Submission Request – FY 2025", from_name: "IMF Statistics Department", from_email: "stats@imf.org", to_emails: ["data@department.gov"], cc_emails: [], body_preview: "The International Monetary Fund kindly requests the submission of your annual economic performance indicators for fiscal year 2025. The data should include GDP contribution by sector, employment rates, and foreign direct investment figures.", body_text: "The International Monetary Fund kindly requests the submission of your annual economic performance indicators for fiscal year 2025. The data should include GDP contribution by sector, employment rates, and foreign direct investment figures.", received_at: "2026-02-14T12:00:00Z", status_in_system: "triaged", mailbox: "", is_read: true, is_starred: false, category: "data_request", suggested_category: "data_request", suggested_priority: "high", has_attachments: true, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-02-19T04:14:23.939Z" },
    { id: "69968e1f9507b606e2e2da90", subject: "Documentary Feature Request – Green Building Initiative", from_name: "Al Jazeera English", from_email: "newsdesk@aljazeera.net", to_emails: ["media@department.gov"], cc_emails: [], body_preview: "Al Jazeera English is producing a documentary series on climate action in the Gulf. We would like to feature your Green Building Standards initiative and would appreciate a guided site visit and interview arrangement.", body_text: "Al Jazeera English is producing a documentary series on climate action in the Gulf. We would like to feature your Green Building Standards initiative and would appreciate a guided site visit and interview arrangement.", received_at: "2026-02-13T09:00:00Z", status_in_system: "new", mailbox: "", is_read: false, is_starred: false, category: "media", suggested_category: "media", suggested_priority: "medium", has_attachments: false, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-02-19T04:14:23.939Z" },
    { id: "69968e1f9507b606e2e2da91", subject: "MoU Renewal: EU-GCC Economic Cooperation Framework", from_name: "European Commission – Trade Directorate", from_email: "trade@ec.europa.eu", to_emails: ["international@department.gov"], cc_emails: ["legal@department.gov"], body_preview: "This is an official notification that the EU-GCC Economic Cooperation MoU signed in 2021 is due for renewal. We request your department to initiate the renewal process and nominate a focal point for negotiations by March 15, 2026.", body_text: "This is an official notification that the EU-GCC Economic Cooperation MoU signed in 2021 is due for renewal. We request your department to initiate the renewal process and nominate a focal point for negotiations by March 15, 2026.", received_at: "2026-02-13T07:30:00Z", status_in_system: "triaged", mailbox: "", is_read: true, is_starred: true, category: "mou", suggested_category: "mou", suggested_priority: "urgent", has_attachments: true, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-02-19T04:14:23.939Z" },
    { id: "69968e1f9507b606e2e2da92", subject: "Invoice Dispute – Sports Center Construction Contract", from_name: "Hassan Al-Marzouqi", from_email: "h.marzouqi@contractor.com", to_emails: ["projects@department.gov"], cc_emails: [], body_preview: "We wish to formally raise a dispute regarding Invoice #2026-SC-018 submitted for the Al Ain Sports Center construction. Payment has been outstanding for 65 days beyond the agreed NET-30 terms, affecting our ability to pay subcontractors.", body_text: "We wish to formally raise a dispute regarding Invoice #2026-SC-018 submitted for the Al Ain Sports Center construction. Payment has been outstanding for 65 days beyond the agreed NET-30 terms, affecting our ability to pay subcontractors.", received_at: "2026-02-12T11:15:00Z", status_in_system: "new", mailbox: "", is_read: true, is_starred: false, category: "complaint", suggested_category: "complaint", suggested_priority: "high", has_attachments: true, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-02-19T04:14:23.939Z" },
    { id: "69968e1f9507b606e2e2da98", subject: "Invitation to G20 Digital Economy Working Group – Riyadh 2026", from_name: "G20 Sherpa Office – Saudi Arabia", from_email: "sherpa@g20.gov.sa", to_emails: ["international@department.gov"], cc_emails: ["protocol@department.gov"], body_preview: "The G20 Presidency is pleased to invite a delegate from your department to participate in the Digital Economy Working Group scheduled for May 2026 in Riyadh. Topics will include AI governance, data privacy frameworks, and cross-border digital services.", body_text: "The G20 Presidency is pleased to invite a delegate from your department to participate in the Digital Economy Working Group scheduled for May 2026 in Riyadh. Topics will include AI governance, data privacy frameworks, and cross-border digital services.", received_at: "2026-02-09T07:00:00Z", status_in_system: "triaged", mailbox: "", is_read: true, is_starred: true, category: "invitation", suggested_category: "invitation", suggested_priority: "urgent", has_attachments: true, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-02-19T04:14:23.939Z" },
    { id: "6979b9a8759638ceaa56e556", subject: "UN Tourism Annual Conference - Invitation", from_name: "UN Tourism Secretariat", from_email: "secretariat@untourism.org", to_emails: ["tourism@department.gov"], cc_emails: [], body_preview: "We are pleased to invite your department to participate in the UN Tourism Annual Conference scheduled for September 2024 in Madrid, Spain...", body_text: "We are pleased to invite your department to participate in the UN Tourism Annual Conference scheduled for September 2024 in Madrid, Spain...", received_at: "2024-06-10T09:30:00Z", status_in_system: "triaged", mailbox: "", is_read: true, is_starred: false, category: "invitation", suggested_category: "invitation", suggested_priority: "high", has_attachments: true, assigned_to_user_id: "6979b622cb93ec17bdd5d627", linked_task_id: "", created_date: "2026-01-28T07:24:24.796Z" },
    { id: "6979b9a8759638ceaa56e558", subject: "Request for Tourism Statistics Data - Q1 2024", from_name: "OECD Tourism Committee", from_email: "tourism.data@oecd.org", to_emails: ["tourism@department.gov"], cc_emails: [], body_preview: "As part of our annual tourism indicators compilation, we kindly request your department to submit the Q1 2024 tourism statistics...", body_text: "As part of our annual tourism indicators compilation, we kindly request your department to submit the Q1 2024 tourism statistics...", received_at: "2024-06-07T11:00:00Z", status_in_system: "converted", mailbox: "", is_read: true, is_starred: false, category: "data_request", suggested_category: "data_request", suggested_priority: "medium", has_attachments: false, assigned_to_user_id: "", linked_task_id: "69858a0204a70322268d2941", created_date: "2026-01-28T07:24:24.796Z" },
    { id: "6979b9a8759638ceaa56e559", subject: "Media Interview Request - Tourism Development", from_name: "Sarah Johnson", from_email: "sarah.johnson@bbc.com", to_emails: ["tourism@department.gov"], cc_emails: [], body_preview: "BBC Travel is preparing a feature on emerging tourism destinations in the Middle East. We would like to request an interview with your department...", body_text: "BBC Travel is preparing a feature on emerging tourism destinations in the Middle East. We would like to request an interview with your department...", received_at: "2024-06-06T16:45:00Z", status_in_system: "new", mailbox: "", is_read: true, is_starred: false, category: "media", suggested_category: "media", suggested_priority: "medium", has_attachments: false, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-01-28T07:24:24.796Z" },
    { id: "6979b9a8759638ceaa56e55a", subject: "MoU Renewal - Tourism Cooperation Agreement", from_name: "International Relations Office", from_email: "mou@tourism.gov.eg", to_emails: ["tourism@department.gov"], cc_emails: ["protocol@department.gov"], body_preview: "This is to inform you that the Memorandum of Understanding between our tourism ministries is due for renewal in August 2024...", body_text: "This is to inform you that the Memorandum of Understanding between our tourism ministries is due for renewal in August 2024...", received_at: "2024-06-05T08:20:00Z", status_in_system: "triaged", mailbox: "", is_read: true, is_starred: false, category: "mou", suggested_category: "mou", suggested_priority: "high", has_attachments: true, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-01-28T07:24:24.796Z" },
    { id: "6979b9a8759638ceaa56e55b", subject: "Complaint: Tour Operator License Issue", from_name: "Mohammed Al-Rashid", from_email: "m.rashid@touroperator.com", to_emails: ["tourism@department.gov"], cc_emails: [], body_preview: "I am writing to express my concern regarding the delay in processing our tour operator license renewal application submitted three months ago...", body_text: "I am writing to express my concern regarding the delay in processing our tour operator license renewal application submitted three months ago...", received_at: "2024-06-04T10:30:00Z", status_in_system: "new", mailbox: "", is_read: true, is_starred: false, category: "complaint", suggested_category: "complaint", suggested_priority: "high", has_attachments: false, assigned_to_user_id: "", linked_task_id: "", created_date: "2026-01-28T07:24:24.796Z" },
  ];

  const notificationPreferences = [
    {
      id: "np_user1",
      user_id: "user1",
      user_email: "ahmed.mansouri@tourism.gov",
      notify_task_assigned: true,
      notify_task_assigned_email: true,
      notify_profile_updated: true,
      notify_routing_rule_changes: true,
      notify_team_performance: true,
      notify_status_changes: true,
      notify_due_soon: true,
      notify_overdue: true,
      email_digest_frequency: "immediate",
      created_date: isoDaysFromNow(-30),
      updated_date: isoDaysFromNow(-2),
    },
  ];

  // Real Notifications from Base44 export
  const notifications = [
    { id: "699547695039943271d522cb", user_id: "user1", type: "due_soon", title: "⏰ Task Due Soon", message: 'Task "Tourism Revenue Analysis Report" is due today', entity_type: "task", entity_id: "699346bd705fa209705e5ac4", is_read: false, is_email_sent: false, created_date: "2026-02-18T05:00:25.522Z" },
    { id: "699547675bbac0e106ce13e5", user_id: "user1", type: "overdue", title: "🚨 Task Overdue", message: 'Task "Cultural Heritage Preservation" is 8 day(s) overdue', entity_type: "task", entity_id: "699346bd705fa209705e5abe", is_read: false, is_email_sent: false, created_date: "2026-02-18T05:00:23.565Z" },
    { id: "69954766f7340d03a5e327ed", user_id: "user2", type: "due_soon", title: "⏰ Task Due Soon", message: 'Task "Digital Marketing Campaign" is due in 2 day(s)', entity_type: "task", entity_id: "699346bd705fa209705e5abc", is_read: false, is_email_sent: false, created_date: "2026-02-18T05:00:22.397Z" },
    { id: "n_system_1", user_id: "user1", type: "assignment", title: "New Task Assignment", message: 'You have been assigned to lead "Smart City Digital Infrastructure".', entity_type: "task", entity_id: "69968d421fdeeacc4c795dfc", is_read: true, created_date: isoDaysFromNow(-5) },
    { id: "n_system_2", user_id: "user2", type: "approval_required", title: "Task Approval Required", message: 'Approval needed for: Water Conservation & Management', entity_type: "task", entity_id: "69968d421fdeeacc4c795e00", is_read: false, created_date: isoDaysFromNow(-2) },
    { id: "n_system_3", user_id: "user3", type: "comment", title: "New Comment", message: 'Ahmed Al-Mansouri commented on "Road Safety & Traffic Management"', entity_type: "task", entity_id: "69968d421fdeeacc4c795e01", is_read: false, created_date: isoDaysFromNow(-1) },
  ];

  // Real Routing Rules from Base44 export
  const routingRules = [
    { id: "6979b9a8759638ceaa56e55c", order: 0, name: "UN Tourism Emails", condition_type: "from_domain", condition_value: "untourism.org", action_type: "add_tag", action_value: "UN Tourism", is_active: true, created_date: "2026-01-28T07:24:24.803Z", updated_date: "2026-02-06T06:26:37.755Z" },
    { id: "6979b9a8759638ceaa56e55d", order: 1, name: "OECD Data Requests", condition_type: "from_domain", condition_value: "oecd.org", action_type: "set_category", action_value: "data_request", is_active: true, created_date: "2026-01-28T07:24:24.803Z", updated_date: "2026-01-28T07:24:24.803Z" },
    { id: "6979b9a8759638ceaa56e55e", order: 2, name: "Meeting Minutes - Arabic", condition_type: "subject_contains", condition_value: "محضر", action_type: "set_category", action_value: "general", is_active: true, created_date: "2026-01-28T07:24:24.803Z", updated_date: "2026-01-28T07:24:24.803Z" },
    { id: "6979b9a8759638ceaa56e55f", order: 3, name: "Invitation Emails", condition_type: "subject_contains", condition_value: "invitation", action_type: "set_category", action_value: "invitation", is_active: true, created_date: "2026-01-28T07:24:24.803Z", updated_date: "2026-01-28T07:24:24.803Z" },
    { id: "6979b9a8759638ceaa56e560", order: 4, name: "Visa Related", condition_type: "subject_contains", condition_value: "visa", action_type: "set_category", action_value: "protocol", is_active: true, created_date: "2026-01-28T07:24:24.803Z", updated_date: "2026-01-28T07:24:24.803Z" },
    { id: "rr_media", order: 5, name: "Media Requests", condition_type: "from_contains", condition_value: "reuters.com", action_type: "set_category", action_value: "media", is_active: true, created_date: isoDaysFromNow(-90), updated_date: isoDaysFromNow(-5) },
    { id: "rr_imf", order: 6, name: "IMF Data Requests", condition_type: "from_domain", condition_value: "imf.org", action_type: "set_category", action_value: "data_request", is_active: true, created_date: isoDaysFromNow(-60), updated_date: isoDaysFromNow(-10) },
    { id: "rr_complaints", order: 7, name: "Citizen Complaints", condition_type: "subject_contains", condition_value: "complaint", action_type: "set_priority", action_value: "high", is_active: true, created_date: isoDaysFromNow(-45), updated_date: isoDaysFromNow(-5) },
  ];

  const subtasks = [
    { id: "st_1", task_id: "69968d421fdeeacc4c795dfc", title: "Complete Phase 1 Fiber Installation", status: "in_progress", order: 0, owner_user_id: "user1", due_date: isoDateOnlyDaysFromNow(5), checklist_items: [{ text: "Install backbone in Zone A", completed: true }, { text: "Install backbone in Zone B", completed: false }], created_date: isoDaysFromNow(-10), updated_date: isoDaysFromNow(-2) },
    { id: "st_2", task_id: "69968d421fdeeacc4c795dfc", title: "Deploy IoT Sensors", status: "not_started", order: 1, owner_user_id: "user2", due_date: isoDateOnlyDaysFromNow(15), checklist_items: [], created_date: isoDaysFromNow(-10), updated_date: isoDaysFromNow(-10) },
    { id: "st_3", task_id: "69968d421fdeeacc4c795dfd", title: "UAT Testing with Pilot Departments", status: "in_progress", order: 0, owner_user_id: "user2", due_date: isoDateOnlyDaysFromNow(3), checklist_items: [{ text: "Test with IT Department", completed: true }, { text: "Test with Finance Department", completed: false }], created_date: isoDaysFromNow(-5), updated_date: isoDaysFromNow(-1) },
  ];

  const comments = [
    { id: "c_1", entity_type: "task", entity_id: "69968d421fdeeacc4c795dfc", comment_text: "Fiber installation in Zone A completed ahead of schedule.", activity_type: "comment", is_system: false, created_by: "ahmed.mansouri@tourism.gov", created_date: isoDaysFromNow(-3) },
    { id: "c_2", entity_type: "task", entity_id: "69968d421fdeeacc4c795dfc", comment_text: "Status updated from not_started to in_progress", activity_type: "status_change", is_system: true, old_value: "not_started", new_value: "in_progress", created_by: "system", created_date: isoDaysFromNow(-20) },
    { id: "c_3", entity_type: "task", entity_id: "69968d421fdeeacc4c795dfd", comment_text: "Portal beta version ready for UAT.", activity_type: "comment", is_system: false, created_by: "fatima.kitbi@tourism.gov", created_date: isoDaysFromNow(-2) },
  ];

  const taskDependencies = [
    { id: "td_1", dependent_task_id: "69968d421fdeeacc4c795dfd", prerequisite_task_id: "69968d421fdeeacc4c795dfc", dependency_type: "finish_to_start", is_active: true, created_date: isoDaysFromNow(-12), updated_date: isoDaysFromNow(-12) },
  ];

  const taskApprovals = [
    { id: "ta_1", task_id: "69968d421fdeeacc4c795e00", approver_user_id: "user1", approver_name: "Ahmed Al-Mansouri", status: "pending", sequence_order: 0, is_sequential: true, created_date: isoDaysFromNow(-2), updated_date: isoDaysFromNow(-2) },
    { id: "ta_2", task_id: "69968d421fdeeacc4c795e05", approver_user_id: "user2", approver_name: "Fatima Al-Kitbi", status: "pending", sequence_order: 0, is_sequential: true, created_date: isoDaysFromNow(-1), updated_date: isoDaysFromNow(-1) },
  ];

  return {
    meta: { seed_version: 2, created_at: new Date().toISOString() },
    auth: { currentUserId: "user1" },
    entities: {
      User: users,
      Department: departments,
      Teams: teamMembers,
      WorkflowStage: workflowStages,
      Initiative: initiatives,
      EmailMessage: emailMessages,
      Notification: notifications,
      NotificationPreference: notificationPreferences,
      RoutingRule: routingRules,
      RolePageAccess: [],
      RolePermission: [],
      Subtask: subtasks,
      Comment: comments,
      TaskDependency: taskDependencies,
      TaskApproval: taskApprovals,
    },
  };
}
